uploads = []

[[generated]]
id = "2oSudi33qGU27SJkrVWvr"
uri = "file://artifacts/lumen-library/src/assets/covers/meditations.png"
type = "image"
title = "Meditations book cover"

[[generated]]
id = "CO2_JcTj3yYBrSgd83woZ"
uri = "file://artifacts/lumen-library/src/assets/covers/atomic-habits.png"
type = "image"
title = "Atomic Habits book cover"

[[generated]]
id = "XlDnGBLBoV-29TBQUW95c"
uri = "file://artifacts/lumen-library/src/assets/covers/thinking-fast.png"
type = "image"
title = "Thinking Fast book cover"

[[generated]]
id = "4711mPmFxg9nofKZUqS9P"
uri = "file://artifacts/lumen-library/src/assets/covers/zero-to-one.png"
type = "image"
title = "Zero to One book cover"

[[generated]]
id = "v0N_V1V8u_tJb5P7DigmT"
uri = "file://artifacts/lumen-library/src/assets/covers/brief-history.png"
type = "image"
title = "Brief History book cover"

[[generated]]
id = "VqRKa7gZJcPjtXHen1Mn1"
uri = "file://artifacts/lumen-library/src/assets/covers/power-of-now.png"
type = "image"
title = "Power of Now book cover"

[[generated]]
id = "YV5CDJA2C0AKWr5oLcN6E"
uri = "file://artifacts/lumen-library/src/assets/covers/principles-of-human-knowledge.png"
type = "image"
title = "berkeley kawaii cover"

[[generated]]
id = "fNiQQwgSEVVuwBuhpT6Mg"
uri = "file://artifacts/lumen-library/public/avatar/girl-reading.png"
type = "image"
title = "girl-reading-avatar"

[[generated]]
id = "-0gmvtnFVtxPIisD0cYW2"
uri = "file://artifacts/lumen-library/public/covers/atomic-habits.png"
type = "image"
title = "generated_image"

[[generated]]
id = "17X1Z8v4DvBqvIMkQlDKJ"
uri = "file://artifacts/lumen-library/public/covers/deep-work.png"
type = "image"
title = "generated_image"

[[generated]]
id = "zmqBHb1oYic44B249MVxb"
uri = "file://artifacts/lumen-library/public/covers/make-time.png"
type = "image"
title = "generated_image"

[[generated]]
id = "PNaI1CaU9iPUc2_ABRW5R"
uri = "file://artifacts/lumen-library/public/covers/subtle-art.png"
type = "image"
title = "generated_image"

[[generated]]
id = "ZdAnbPKvdCJ3gk65aSLyJ"
uri = "file://artifacts/lumen-library/public/covers/the-5-am-club.png"
type = "image"
title = "generated_image"

[[generated]]
id = "HZdxuWy3DGLBXGKAaXxbB"
uri = "file://artifacts/lumen-library/public/covers/12-rules-for-life.png"
type = "image"
title = "generated_image"

[[generated]]
id = "mkP18EpnRsxx-mk5t_-FI"
uri = "file://artifacts/lumen-library/public/covers/everything-is-fcked.png"
type = "image"
title = "generated_image"

[[generated]]
id = "tjZtMW7Zcxub1k5IAcaHm"
uri = "file://artifacts/lumen-library/public/covers/12-week-year.png"
type = "image"
title = "generated_image"

[[generated]]
id = "9JUkS8uPWSHe04ZSp_pF_"
uri = "file://artifacts/lumen-library/public/covers/cant-hurt-me.png"
type = "image"
title = "generated_image"

[[generated]]
id = "7HuCWPSr8Bn2hscpQ6Z7a"
uri = "file://artifacts/lumen-library/public/covers/essentialism.png"
type = "image"
title = "generated_image"

[[generated]]
id = "VUqLzPi-FunZlnySwlbTY"
uri = "file://artifacts/lumen-library/public/covers/personal-mba.png"
type = "image"
title = "generated_image"

[[generated]]
id = "4LCieo4wU6mgUh1-n28vv"
uri = "file://artifacts/lumen-library/public/covers/lean-startup.png"
type = "image"
title = "generated_image"

[[generated]]
id = "Bo3CWRFRBDGIxALdeNxZb"
uri = "file://artifacts/lumen-library/public/covers/think-and-grow-rich.png"
type = "image"
title = "generated_image"

[[generated]]
id = "MGI7LirvJaMMZGs8pvobX"
uri = "file://artifacts/lumen-library/public/covers/millionaire-fastlane.png"
type = "image"
title = "generated_image"

[[generated]]
id = "BGZ_62WtQuP5RpNsQVQmS"
uri = "file://artifacts/lumen-library/public/covers/rich-dad-poor-dad.png"
type = "image"
title = "generated_image"

[[generated]]
id = "emhY03Z1J9guryM8xo1hD"
uri = "file://artifacts/lumen-library/public/covers/tools-of-titans.png"
type = "image"
title = "generated_image"

[[generated]]
id = "ttydD-VMONdwTJlEx0fvW"
uri = "file://artifacts/lumen-library/public/covers/almanack-naval.png"
type = "image"
title = "generated_image"

[[generated]]
id = "OUnni-V6M14zI5z7j9fxH"
uri = "file://artifacts/lumen-library/public/covers/4-hour-work-week.png"
type = "image"
title = "generated_image"

[[generated]]
id = "NH8skWZlj2jXsCudGaMYP"
uri = "file://artifacts/lumen-library/public/covers/innovators-dilemma.png"
type = "image"
title = "generated_image"

[[generated]]
id = "9-GFiicDClKpuJUgC_RhB"
uri = "file://artifacts/lumen-library/public/covers/thinking-fast-and-slow.png"
type = "image"
title = "generated_image"

[[outputs]]
id = "mda2YjDF63hrzLNtUKxKm"
uri = "file://artifacts/lumen-library/dist/lumen-neocities.tar.gz"
type = "unspecified"
title = "Lumen — static build for Neocities (extract & upload)"
