uploads = []

[[generated]]
id = "2oSudi33qGU27SJkrVWvr"
uri = "file://artifacts/lumen-library/src/assets/covers/meditations.png"
type = "image"
title = "Meditations book cover"

[[generated]]
id = "CO2_JcTj3yYBrSgd83woZ"
uri = "file://artifacts/lumen-library/src/assets/covers/atomic-habits.png"
type = "image"
title = "Atomic Habits book cover"

[[generated]]
id = "XlDnGBLBoV-29TBQUW95c"
uri = "file://artifacts/lumen-library/src/assets/covers/thinking-fast.png"
type = "image"
title = "Thinking Fast book cover"

[[generated]]
id = "4711mPmFxg9nofKZUqS9P"
uri = "file://artifacts/lumen-library/src/assets/covers/zero-to-one.png"
type = "image"
title = "Zero to One book cover"

[[generated]]
id = "v0N_V1V8u_tJb5P7DigmT"
uri = "file://artifacts/lumen-library/src/assets/covers/brief-history.png"
type = "image"
title = "Brief History book cover"

[[generated]]
id = "VqRKa7gZJcPjtXHen1Mn1"
uri = "file://artifacts/lumen-library/src/assets/covers/power-of-now.png"
type = "image"
title = "Power of Now book cover"

[[generated]]
id = "YV5CDJA2C0AKWr5oLcN6E"
uri = "file://artifacts/lumen-library/src/assets/covers/principles-of-human-knowledge.png"
type = "image"
title = "berkeley kawaii cover"

[[outputs]]
id = "mda2YjDF63hrzLNtUKxKm"
uri = "file://artifacts/lumen-library/dist/lumen-neocities.tar.gz"
type = "unspecified"
title = "Lumen — static build for Neocities (extract & upload)"
